_posts/continuous-deployment/2014-09-03-deployment-with-custom-scripts.md

Helps sentence to read clearly.

Grammar fix

---

_posts/languages/2014-09-03-go.md

Based on feedback from a user. @ngauthier please take a look and let me know if this is fine!

Include test dependencies for go get

---

_posts/languages/2014-09-03-ruby.md

Just a little grammar fix to make the sentence read a little better.

Grammar update

---

_posts/languages/2014-09-03-nodejs.md

added npm grunt testnote

---

_includes/footer.html
_includes/header.html

Now has indent Header structure to the marketing pages

Updated Header Links

---

_posts/continuous-integration/2014-09-03-keep-build-artifacts.md

and also reference the integrated S3 deployment option. Fixes #198

Update article on keeping build artifacts

---

_posts/integrations/2014-09-02-webhooks.md

@beanieboi could you take a look if this is fine?

Update build status documentation

---

_posts/continuous-integration/2015-01-20-parallelci.md

Information about the upcoming ParallelCI trial.

Information on the ParallelCI trial

---

_includes/mixpanel.html

This PR adds the missing properties for episode 3 (see https://trello.com/c/TUOchySl/654-new-mixpanel-tracking-episode-3-extend-the-current-tracking-to-all-other-public-pages) and removes old code (see https://trello.com/c/N5GCC0Wy/708-new-mixpanel-tracking-episode-9-remove-old-events).

Feature: Various mixpanel updates and fixes

---

_posts/continuous-deployment/2015-04-24-push-to-remote-repository.md
_posts/faq/2014-09-10-push-to-remote-repositories.md

This needs codeship/scripts#33 first.

Rewrite documentation for pushing to remote repositories

---

_posts/languages/2014-09-03-python.md

Rework the commands for the Python 3 version of the virtual environment to be compatible with the dependency cache and make it easier to use.

Update commands to use Python3

---

_sass/docs/_page.scss

fix for nested ul elements in ol

---

_posts/continuous-deployment/2015-06-16-deployment-to-aws-lambda.md

Needs some adaptations for the deployment script in at the end.

Basic Documentation for deploying to AWS Lambda

---

_posts/continuous-deployment/2014-09-03-deployment-to-heroku.md

Update Heroku deployment to specify the --exit-code option

---

_posts/services/databases/2015-09-24-rethinkdb.md

https://codeship.com/projects/102044/builds/c85d4e3b-5192-4ed4-95ac-0ce708bcb0fe

adding rethinkDB doc

---

_posts/continuous-deployment/2014-09-03-deployment-to-google-app-engine.md

@mlocher @BoVice feedback appreciated

update GAE docs to include issues regarding refresh token

---

_data/categories/docker-integration.yml
_data/categories/docker.yml
_posts/docker/2015-05-25-introduction.md

Sample screenshot from a category index page

Mention the invite only nature of the Docker platform

---

_posts/docker/2015-05-25-services.md
_posts/docker/tutorials/2015-09-04-docker-volumes.md

see codeship/codeship-tool-examples#15

Use two digit example numbering

---

_posts/continuous-integration/2014-09-03-skipping-builds.md
_posts/continuous-integration/2014-09-03-ssh-access.md
_posts/docker/jet/2015-05-25-cli.md

Clear up some stuff that isn't yet available on jet. Each of the changes comes from a support request.

Clearer jet instructions

---

_posts/docker/deployments/2015-08-31-google-cloud.md

Fixed typo in docs

---

_posts/docker/2015-05-25-services.md

Update the list of unavailable features with respect to the 1.6.0 update to Docker Compose.

Update unavailable Docker Compose features.

---

CODE_OF_CONDUCT.md

there are couple new versions of the CoC. this updates to the latest version from http://contributor-covenant.org/.
it includes good examples and is more expressive in every way.

update CoC to the latest version

---

_posts/services/queues/2014-08-28-redis.md

2.8.4 is currently installed on the build VMs.

Update the Redis version

---

_posts/services/2014-08-28-elasticsearch.md
_posts/services/databases/2015-09-24-rethinkdb.md
_posts/services/databases/2016-02-04-cassandra.md

Elasticsearch and RethinkDB start documentation

Elasticsearch and RethinkDB start documentation

---

_posts/continuous-deployment/2014-09-03-deployment-to-elastic-beanstalk.md

Add missing ElasticBeanstalk permission

---

_posts/languages/2014-09-03-php.md

Add information about upgrading the installed version of PHPUnit on the classic build VMs.

Docs for installing a custom PHPUnit version

---

_posts/languages/2014-09-03-nodejs.md

* Also some minor cleanup / improvements

Updated available NodeJS versions

---

_posts/services/databases/2014-08-28-postgresql.md

* Add details for how to connect to 9.5
* Add information on different PostGIS version on 9.5 vs 9.2 to 9.4
* Various cleanup and rewording efforts

Add PostgreSQL 9.5 information

---

_posts/docker/2015-06-10-getting-started.md
_posts/docker/jet/2015-05-25-installation.md

Those are small improvements/fixes I'm finding while reading the documentation.

Documentation better naming

---

_posts/docker/tutorials/2015-08-12-docker-pull.md

Adding a few common issues to the doc for troubleshooting purposes.

Adding common problems to private base image

---

_posts/docker/tutorials/2015-09-07-caching.md

Fixing anchor link (had defined it with base url tag incorrectly)

Cache link update

---

Gemfile.lock
_posts/docker/jet/2015-05-25-cli.md
_posts/docker/jet/2015-05-25-installation.md

Putting more explanation for what/why regarding Jet and creating a link between the two key articles.

Updating CLI and Installation articles with context and crosslinks

---

_posts/continuous-integration/2014-09-03-set-environment-variables.md

Clarify which chars are escaped when using the environment settings

---

_includes/comments.html

Reverts codeship/documentation#423

Revert "added meta data to stop comments from being indexed and followed"

---

_posts/docker/tutorials/2015-07-03-docker-push.md

I think Quay may have changed their UI, so I updated our docs to reflect the new workflow.

More specific instructions for robot account credential retrieval

---

_posts/docker/2015-05-25-steps.md
_posts/docker/jet/2015-05-25-installation.md
templates/tutorial-template.md

Moving TOC in template
Minor adjustment to templatize Installation doc
Minor adjustment to templatize Steps doc

Templatizing articles

---

_posts/docker/tutorials/2015-09-07-caching.md

**do not merge**
To be merged when the new caching feature is released to the masses.

Updating caching tutorial for new caching strategy

---

_posts/docker/jet/2015-05-25-cli.md
_posts/docker/tutorials/2015-09-07-caching.md

*do not merge*
Depends on https://github.com/codeship/jet/pull/195

Updating docs to reflect deprecation of remote caching flag

---

_includes/head.html

Allows Marketing to use https://www.addthis.com/get/welcome-bar for announcements.

Add AddThis functionality

---

bin/notify_slack.sh

* Print the payload as a log message
* Switch curl from silent to verbose mode

Get more debugging information on Slack notifications

---

_posts/docker/tutorials/2015-09-07-caching.md

Do not merge until https://github.com/codeship/jet/pull/240

adding default cache branch directive

---

Dockerfile.aws

It's now called `robots.txt` and there is no special handling any longer.

Don't copy _robots.txt

---

Dockerfile
_includes/footer.html
bin/build.sh
bin/s3.sh
robots.txt

* Remove duplicate deployments for the `master` branch
* Fix an issue reported by the `Dockerfile` linter

Cleanup after moving to documentation.codeship.com

---

_posts/docker/guide/2015-06-10-getting-started.md

Fix syntax error in Dockerfile

---

_posts/docker/2016-08-31-community-images.md

There is a positioning issue with links in headings, to work around I switched to a nested list for now.
See http://d.pr/i/17Wu6 for a screenshot.

Work around a CSS image with links in headings

---

_posts/integrations/2014-09-02-api.md

Also, fix a bug with the article not showing up on the index pages, because of a wrongly capitalized category name

Add info message regarding API and the Docker platform

---

_includes/footer.html

Hi,
this is fixing the footer links to use absolute instead of relative paths.
Best,
Roman

Updated Paths

---

_posts/docker/tutorials/2015-12-17-dockercfg-services.md

Required for codeship-library/aws-deployment#17

Update the URL for the AWS dockercfg generator

---

README.md
_posts/services/databases/2014-08-28-postgresql.md

Fixed a couple typos

---

_includes/header.html

There is another header link that needs update.
Best,
Roman

Fixed link

---

_includes/footer.html
_includes/head.html
_sass/docs/_footer.scss

Hello,
this PR updates the footer in updating the wording of a link, adding a link to the swag page, removing one and also updating the font to use Lato.
Thanks

Updated Footer

---

_includes/header.html

Hi,
this PR fixes the resources link in the header.
thanks

Update Resources Link in Header

---

_posts/docker/2015-05-25-steps.md

Added updated directives to the group steps, included in example.

Add directives to group steps

---

_includes/footer.html

Hi eveyone,
Added the Contact Support Link to the footer on request of Marketing.
https://www.pivotaltracker.com/story/show/132696169
thanks

Added Contact Support Link

---

_posts/administration/2016-03-17-invoices.md
_posts/continuous-integration/2014-09-03-skipping-builds.md
_posts/docker/2016-10-21-skipping-builds.md
_posts/docker/2016-10-25-image-push-fails.md
_posts/faq/2014-09-10-limit_builds.md
_posts/faq/2015-05-19-configure-your-avatar.md

* added information about skipping builds to limiting builds FAQ
* corrected some mistakes in invoices and avatar FAQ
* added article about image push fails as suggested by @ethangj

Fix some FAQ content, add article

---

_sass/docs/_page.scss

Reverts codeship/documentation#522

Revert "Fix vw caused rounding error"

---

_website.json

Redirect 2 old links

---

_classic/continuous-deployment/deployment-to-google-app-engine.md
_classic/continuous-deployment/deployment-with-capistrano.md
_classic/continuous-deployment/deployment-with-custom-scripts.md
_docker/getting-started/codeship-configuration.md
_docker/getting-started/docker-volumes.md
_general/projects/enabling-access-to-servers.md

some from before restructuring, some after

Fix in-documentation broken links

---

_docker/getting-started/services.md
_website.json

* removed path: app in all but one example for cleaner examples (as requested by Ethan)
* 2 redirects

Fix 2 links and clean up an article

---

_website.json

Fix 1 link

---

404.md
_classic/getting-started/beanstalkd.md
_classic/getting-started/sqlite.md
_general/about/security.md
_general/account/github-3rd-party-restrictions.md
_general/account/invoices.md
_general/projects/builds-are-not-triggered.md
_general/projects/cant-find-file-in-repository.md
_general/projects/enabling-access-to-servers.md
_general/projects/no-such-file-or-directory-config-yourconfigyml.md
_general/projects/pending-step-in-cucumber-fails-build.md
_general/projects/push-to-remote-repositories.md
docker/index.md

Add some more redirects which were brought to our attention.

Missing redirects brought up by the SEO agency

---

_classic/languages-frameworks/nodejs.md

#551 was using the directory structure before the re-categorization. This PR re-applies the changes so we can merge them.

Re-apply changes from #551

---

_classic/continuous-deployment/deployment-with-ftp-sftp-scp.md

* reorganised structure
* added some more information
* missing: graphics

Clarify FTP article

---

_classic/continuous-deployment/deployment-to-elastic-beanstalk.md

Closes #450, thanks to https://github.com/alemhnan for pushing the initial PR

Update Elastic Beanstalk IAM policies

---

_docker/getting-started/steps.md

The base functionality is in Jet, but the UI updates have not been pushed to Mothership.
https://www.pivotaltracker.com/story/show/106991536

Adding docs for excluding a step

---

_includes/hubspot.html
_layouts/default.html

Add HubSpot analytics to the documentation.

Add Hubspot analytics tracking

---

_classic/getting-started/timezone.md

This question is still brought up enough times in support requests that an article should be available to address how to set this up.

Article for setting up a different time zone

---

_classic/getting-started/timezone.md

Fixed a couple links and the command syntax.

Update timezone doc

---

_classic/continuous-deployment/deployment-with-awscli.md
_classic/getting-started/api.md
_classic/getting-started/ssh-access.md
_data/categories/docker-guide.yml
_data/categories/docker-integration.yml
_data/categories/docker.yml
_docker/continuous-integration/browser-testing.md
_docker/getting-started/codeship-configuration.md
_docker/getting-started/docker-pull.md
_docker/getting-started/getting-started-part-three.md
_docker/getting-started/installation.md
_docker/languages-frameworks/go.md
_docker/languages-frameworks/java.md
_docker/languages-frameworks/nodejs.md
_docker/languages-frameworks/python.md
_docker/languages-frameworks/ruby.md
_general/projects/limit_builds.md
classic/index.md
docker/index.md

* renamed hopefully all occurrences of Classic/Docker to Basic/Pro
* not included: file names, folder names, titles, redirects

Rename Classic/Docker occurrences into Basic/Pro

---

_pro/getting-started/installation.md

Take two on fixing this redirect. 🎬

Fix redirect for bit.ly/codeship-jet-tool

---

_general/about/mobile-support.md

I'm assuming Marko/Jason/Joe will have suggestions for improving the language of this, but wanted to get a draft going.

Adding mobile support article draft one.

---

_pro/getting-started/build-arguments.md
_pro/getting-started/handling-secrets.md

Hey all,
It would help our customers to have a documentation article that aggregated all information related to handling secrets during Codeship Pro builds. Here is that article :)
https://www.pivotaltracker.com/story/show/135840341
@ethangj -- it's all yours! Let me know if you'd like any more code examples.

Add Handling Secrets docs article

---

_basic/databases/postgresql.md

Adding some info for dealing with `pg_dump` errors in your build on Codeship Basic

Adding pg_dump info

---

_pro/getting-started/handling-secrets.md

Not ideal, but is a quick workaround. May inspect further if I have some downtime.

adding quick fix around unexpected a:hover

---

_pro/getting-started/getting-started-part-three.md

Not sure about the bolding of the text in the bracket?

updating guide to say that pro is now free

---

_basic/getting-started/api.md

Launching when Dennis is ready

Updating API article with Stoplight link

---

_pro/continuous-deployment/heroku.md

updated info block to say Heroku instead of Google Cloud

updated info block to say Heroku

---

_pro/getting-started/docker-volumes.md

i'll do a separate PR for removing the warning tomorrow - just noted the incorrect date and also realized that 1.13 != 17.03.01 :/

minor update to release date and version

---

_pro/getting-started/docker-volumes.md

this shouldn't be merged until the upgrade has happened

removing warning about upgrade to 1.13

---

CODE_OF_CONDUCT.md

Update maintainers listed in CoC

---

_pro/continuous-deployment/azure.md

Still to come, splitting Azure into multiple posts, but adding here for now.

Adding Kubernetes repo example link to Azure doc

---

_pro/getting-started/steps.md

These files are not really used anymore and cause confusion

removing reference to old jet-steps files

---

_basic/getting-started/api.md

updated link to API documentation

---

_includes/sidebar.html
_pro/getting-started/build-arguments.md
_pro/getting-started/caching.md
_pro/getting-started/cli.md
_pro/getting-started/cloning-repos.md
_pro/getting-started/codeship-configuration.md
_pro/getting-started/community-images.md
_pro/getting-started/custom-notifications.md
_pro/getting-started/docker-volumes.md
_pro/getting-started/environment-variables.md
_pro/getting-started/getting-started-part-five.md
_pro/getting-started/getting-started-part-four.md
_pro/getting-started/getting-started-part-three.md
_pro/getting-started/getting-started-part-two.md
_pro/getting-started/getting-started.md
_pro/getting-started/handling-secrets.md
_pro/getting-started/image-push-fails.md
_pro/getting-started/image-registries.md
_pro/getting-started/installation.md
_pro/getting-started/migrating-basic-to-pro.md
_pro/getting-started/release-notes.md
_pro/getting-started/services-and-databases.md
_pro/getting-started/services.md
_pro/getting-started/steps.md

Seems bigger than it is, a small modification to sidebar sorting and then weights in one category.

Fixing sidebar sorting and sorting Pro getting started

---

_general/account/permissions.md

also fixed minor grammatical error...

added specific scopes for github

---

_pro/continuous-deployment/azure.md

Remove reference to the Docker engine

---

bin/build.sh

I believe this is where we want to shuttle the release notes?

Update paths to release notes in build.sh

---

_layouts/tags.html
_plugins/tag_pages.rb

@mlocher this reinstates tag views (which works!) but the build fails with url conflict errors related to tags. would be great if you could take a look at how to resolve these conflicts as i'm stuck (no rush)

Reinstating tag views, but broken build

---

_pro/builds-and-configuration/cli.md

Linked to on https://codeship.com/features/pro

Add missing redirect for Jet CLI installation

---

_basic/builds-and-configuration/dependency-cache.md
_basic/languages-frameworks/python.md

For review @dennisnewel @mlocher

Draft python updates

---

_pro/builds-and-configuration/steps.md

Add redirect from old dockercfg-services page.

---

_general/projects/project-ssh-key.md

typo fix on project-ss-key page

---

_basic/builds-and-configuration/parallelci.md
_general/integrations/codeclimate.md
_general/integrations/coveralls.md
_general/integrations/opsgenie.md
_general/integrations/percy.md
_general/integrations/rollbar.md
_general/integrations/sourceclear.md

@mlocher Do you know if we have, or if you could quickly write, a very simple script that just shows something like a simple if with a real deployment command (like s3 or heroku)? I think it's optional in the scope of this, and I don't see one sitting around, was just curious if we had anything prepared already to bump this up a bit in depth.

OpsGenie draft

---

_basic/languages-frameworks/meteor.md

Trimmed down version of Node.js doc, messaging adjusted for meteor service.

basic meteor doc

---

_general/projects/getting-started.md

Fixed typo

---

_pro/builds-and-configuration/image-registries.md
_pro/builds-and-configuration/steps.md
_pro/languages-frameworks/go.md
_pro/languages-frameworks/java.md
_pro/languages-frameworks/nodejs.md
_pro/languages-frameworks/php.md
_pro/languages-frameworks/python.md
_pro/languages-frameworks/ruby.md
_pro/quickstart/getting-started-part-three.md

Also changing `container` to `image`.

Pinning example Dockerfile to a version

---

_includes/segment.html

Tested locally for js errors and verified data coming through segment as intended.

Adding category to Segment event

---

_general/integrations/brakeman.md

Brakeman OSS: http://brakemanscanner.org
Brakeman Pro SaaS Product: https://brakemanpro.com

Added "Pro" to all Brakeman mentions to avoid confusion

---

_general/integrations/percy.md

Found small mistake on percy pro docs

missing words on percy doc

---

_basic/builds-and-configuration/parallel-tests.md
_basic/languages-frameworks/dart.md
_basic/languages-frameworks/elixir.md
_basic/languages-frameworks/go.md
_basic/languages-frameworks/java-and-jvm-based-languages.md
_basic/languages-frameworks/meteor.md
_basic/languages-frameworks/nodejs.md
_basic/languages-frameworks/php.md
_basic/languages-frameworks/python.md
_basic/languages-frameworks/ruby.md
_basic/languages-frameworks/rust.md
_general/integrations/codeclimate.md
_general/integrations/sourceclear.md
basic/index.md
index.html

Removing parallelci from docs

---

_pro/continuous-deployment/google-cloud.md
_pro/continuous-deployment/google-container.md

Amongst the other refactoring I forgot the actual original task.

Public key clarification Gcloud

---

_basic/builds-and-configuration/packages.md
_pro/continuous-deployment/google-cloud.md
_sass/docs/_page.scss
_sass/rig/_variables.scss
assets/css/docs.scss

Boxes are more compact, colors are adapted to the current style guide, icon for the warning block is updated to http://fontawesome.io/icon/exclamation-triangle/
New info box (old one below)
New warning box
Happy to get some feedback :)

Update the styling of alert (info & warning) boxes

---

Gemfile
Gemfile.lock
_config.yml
_layouts/redirect.html
yarn.lock

Let's get us back on the latest Jekyll release.

Jekyll 3.5.1

---

_basic/continuous-deployment/deployment-to-digitalocean.md

https://trello.com/c/qafBcR6y/219-improve-cd-to-digital-ocean-basic-article

updated digitalocean basic deployment

---

.dockerignore
CONTRIBUTING.md
README.md
SUPPORT.md
_config.yml

See https://github.com/blog/2400-support-file-support for the announcement from GitHub

Add a SUPPORT.md file

---

404.md
_layouts/error.html

* Don’t show the reading time indicator
* Don’t show the feedback block
* Update text slightly

Update 404 page

---

_includes/read_time.html
_sass/docs/_page.scss

* Base it on the CSS of the info/warning/feedback blocks
* White background
* Clock icon

Small refactor of the reading time indicator

---

Rakefile
yarn.lock

* Add a Rake task to pull the latest version of the base image, which is automatically called prior to updating the dependencies
* Update NPM based dependencies

Dependency updates

---

_basic/builds-and-configuration/parallel-tests.md
_basic/continuous-deployment/deployment-with-ftp-sftp-scp.md
_pro/continuous-deployment/ssh-deploy.md
_pro/continuous-integration/parallel-pro.md

Add tags for some common Swiftype queries that didn't bring up any results.

Swiftype no results

---

_pro/continuous-deployment/google-cloud-functions.md

fixed broken link

---

_basic/builds-and-configuration/deployment-pipelines.md

Did I get this right @dennisnewel?

Add deployment wildcard trick

---

_pro/quickstart/getting-started-part-three.md

gathering docker creds for mac os, added to quickstart

---

_basic/continuous-integration/keep-build-artifacts.md

https://trello.com/c/iDXBrQQA/292-1-artifacts-add-more-clear-answer-about-us-not-storing

clarification of no artifact implementation on Codeship's end

---

_pro/continuous-deployment/ibm-bluemix-cloudfoundry.md

Pending deployment container work.

IBM cloudfoundry

---

_pro/builds-and-configuration/cloning-repos.md

Same as https://github.com/codeship/documentation/pull/977, one more place to add code snippet.

docker run command to format ssh key into one line

---

_general/projects/getting-started.md

Small wording change that caused some confusion in a ticket.

Change bastion wording

---

_data/docker.yml

Reflect production docker version

---

_config.yml
_includes/head.html

See: https://developers.google.com/search/docs/data-types/corporate-contacts

Meta tag contact info

---

_basic/builds-and-configuration/packages.md
_includes/head.html
_pro/continuous-deployment/hashicorp-terraform.md
index.html
robots.txt

Finally add some Terraform article(s) to our documentation for Codeship Pro

Initial stab at a Pro/Terraform article

---

_layouts/page.html
_sass/docs/_page.scss

Using Wufoo account I created, figure we can leave it up a few weeks and see what happens and then optimize.

Adding feedback form to end block

---

.spelling
_basic/builds-and-configuration/api.md
_pro/builds-and-configuration/cloning-repos.md

considering this the initial draft
LMK if i've missed something

update to API "landing page" on documentation

---

_basic/quickstart/getting-started.md
_general/account/notifications.md
_general/projects/getting-started.md

mainly just mentioning the API on some of the pages listed https://trello.com/c/np5ZdfFW/362-1-docs-api-changes

Couple of extra API updates

---

_data/docker.yml

Reverts codeship/documentation#1063

Revert "Update published Docker version to 17.10"

---

_general/about/vm-and-infrastructure.md

Timeout length

---

_pro/builds-and-configuration/services.md

clarify that we indeed support volumes, just not for top level keys

---

_pro/languages-frameworks/elixir.md

How do we feel about sample project being on my own org? Do we want to get that moved to `codeship-library`?
https://trello.com/c/j5oRIsm2/113-elixir-docker-codeship

pro elixir documentation

---

_basic/quickstart/getting-started.md
_general/integrations/api.md
_general/projects/getting-started.md
_pro/builds-and-configuration/cloning-repos.md

Updating the content a bit and changing the section about API v1 to mention deprecation
should hold off on deploying this until API release date

Api page update

---

_general/integrations/api.md

also trying to fix the redirect; not sure it'll work though?

moving page into Integrations menu

---

_general/integrations/api.md

includes link to the Go library/client

added section on API clients

---

_pro/builds-and-configuration/cli.md

Thanks for spotting the typo, @markphelps

Fix a typo with macOS Homebrew updates

---

_pro/jet-cli/update.md

adding a Note section to update docs article that this command is available only after updating to Jet CLI 2.2.0+

adding a Note section

---

_pro/builds-and-configuration/services.md

Blocked pending merge of the fix for this.

heathcheck clarify

---

_pro/builds-and-configuration/build-arguments.md

CI env vars as build args

---

_general/about/2fa.md

the question came up on the community slack channel

adding section on 2FA and the API

---

.spelling
_basic/databases/postgresql.md

not to be merge until Feb 21 AM ET

adding deprecation notice for 9.2 and new section on 10.2

---

.spelling
_basic/continuous-integration/browser-testing.md

New Basic version needs to go out first.

Frontend updates

---

_general/integrations/codeclimate.md

Trying to sync up with changes on https://docs.codeclimate.com/docs/codeship-ci-test-coverage-example

Code Climate updates

---

bin/s3.sh

based on AWS documentation available at https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

Adapt the CloudFront invalidation

---

_pro/builds-and-configuration/steps.md

Blocked pending build page release.

On fail docs

---

.spelling
_pro/jet-cli/decrypt.md
_pro/jet-cli/encrypt.md

Updating docs for yet to be released new version of Jet encrypt/decrypt that includes data signing.
See https://github.com/codeship/jet/issues/624 for more info

Updating docs for new version of jet encrypt/decrypt

---

_general/about/security.md

missed a very important detail on the security page; we're not a processor int he eyes of GDPR

we're not a processor

---

_pro/quickstart/getting-started-part-four.md
_pro/quickstart/getting-started-part-three.md
_pro/quickstart/getting-started.md

Fixes to this guide: https://documentation.codeship.com/pro/quickstart/getting-started/
**Part 1:** Solve Redis image name discrepancy
**Part 3:** Add warning about not committing your AES key - @ethangj is `csnote warn` a real thing? I guessed at that based on the `csnote info`.
**Part 4:** Solve container directory discrepancy

Pro intro guide fixes

---

_general/integrations/opsgenie.md
_general/projects/notifications.md
_pro/builds-and-configuration/steps.md
integrations/index.html

missed the article as it was under `account` and not `projects` - it's a project level setting and should be there :)

updated with Stride and moved to projects category

---

_layouts/page.html

Removing polldaddy and wufoo

---

.spelling
_pro/continuous-deployment/aws-codedeploy.md
_pro/continuous-deployment/aws-eks.md
_pro/continuous-deployment/aws.md
_pro/continuous-deployment/azure.md
_pro/continuous-deployment/deployment-with-kubernetes.md
_pro/continuous-deployment/docker-swarm.md
_pro/continuous-deployment/google-app-engine.md
_pro/continuous-deployment/google-cloud-functions.md
_pro/continuous-deployment/google-cloud.md
_pro/continuous-deployment/google-compute-engine.md
_pro/continuous-deployment/google-container.md
_pro/continuous-deployment/hashicorp-terraform.md
_pro/continuous-deployment/heroku.md
_pro/continuous-deployment/ibm-bluemix-cloudfoundry.md
_pro/continuous-deployment/ibm-bluemix-container-service.md
_pro/continuous-deployment/ssh-deploy.md

Lightweight initial EKS documentation that we can flesh with for more specifics later

EKS documentation v1

---

_basic/languages-frameworks/php.md
_basic/languages-frameworks/ruby.md

One with is enough

---

_pro/languages-frameworks/java.md

https://codeship.zendesk.com/agent/tickets/22588

corrected multistage name

---

_pro/common-issues/jet-pro-disjoint.md
_pro/jet-cli/usage-overview.md

jet / pro disjoints discussed

---

_pro/common-issues/caching-multi-stage-dockerfile.md

caching multi stage dockerfile

---

.spelling
_basic/builds-and-configuration/set-environment-variables.md
_general/projects/build_trigger.md
_pro/builds-and-configuration/environment-variables.md

Fix PR environment variables

---

_includes/footer.html

Appears this case study has been removed

Remove Product Hunt link from footer

---

_general/account/new-user-signup.md

This updates the "Signing up for a new account" page.

This updates the signing up for a new account page.

---

_basic/languages-frameworks/php.md

updated specific versions of PHP

---

_basic/quickstart/getting-started.md

This updates the spelling from Codeship to CodeShip

---

_pro/quickstart/getting-started-part-five.md
_pro/quickstart/getting-started-part-four.md
_pro/quickstart/getting-started-part-three.md
_pro/quickstart/getting-started-part-two.md
_pro/quickstart/getting-started.md

*This change updates the headlines in the Getting Started Guid for CodeShip Pro

This change updates the headlines in the Getting Started Guide.

---

_general/projects/build_trigger.md

picture was on the right side of the page.

fixed picture spacing

---

_pro/continuous-deployment/aws-s3.md

This updates ListBucket to have permission to the bucket SHIP-1238

This updates ListBucket to have permission to the bucket, SHIP-1238

---

_general/integrations/appranix.md

Updating for the upcoming Appranix webinar

Update Appranix title

---

.spelling
_pro/builds-and-configuration/environment-variables.md

This adds content about the GitHub Token Scanning feature. [SHIP-1297]
[SHIP-1297]: https://cloudbees.atlassian.net/browse/SHIP-1297

This adds content about the GitHub Token Scanning feature.

---

_pro/builds-and-configuration/environment-variables.md

Update documentation to include only a single regex pattern that GitHub will match on.

Change token scanning regex documentation

---

_pro/continuous-deployment/deployment-with-kubernetes.md

Change confirmed by user. https://github.com/codeship-library/kubectl

Fixed documentation to match with example repo

---

_general/about/2fa.md

for customers and support to be aware of when 2FA is returning errors.

adding note about clock for enabling 2FA
