- _posts/continuous-deployment/2015-04-24-push-to-remote-repository.md
This fixes an issue where the link to Machine Users Documentation was being treated as relative, resulting in a 404 on the Codeship documentation page.
> Should properly link to machine user documentation

- CONTRIBUTING.md
http://learn.github.com/p/branching.html is no longer a valid link. Below was the closes how-to link on Github that I could find:
https://github.com/blog/1377-create-and-delete-branches
> Fixing broken link

- codeship-services.yml
- codeship-steps.yml
Implement caching for the AWS container. It differs from https://github.com/codeship-library/aws-deployment, because we need the `natsort` Python package to implement the automatic ChangeLog generation for Codeship CLI.
> Cache the AWS container

- Dockerfile
- Dockerfile.node
- Gemfile
- Gemfile.lock
- codeship-services.yml
- codeship-steps.yml
- npm-shrinkwrap.json
Switch to a Alpine based build container (because the standard Ruby container used about 310m of space)
**Assumptions**: Dependencies for this project don't change that often
**Steps**
* Only install required dev packages and purge them after the gem / npm installation again
* Don't install gem documentation
* Switch back to a Node.js installation (as therubyracer is broken on Alpine)
* Run the Gulp steps on the same container
This brought build times without deployment down to about 2 minutes (if the cache can be used), deployments down to about 3 minutes (again with the cache).
Further improvements can be made by caching the AWS and CURL containers as well.
> Switch to Alpine Linux

- bin/build.sh
- bin/check_fork.sh
- codeship-steps.yml
Reason being, that e.g. our `documentation-private` fork, could overwrite the master documentation with outdated information.
Also fix the RegEx for running deployments.
> Fail builds on `master` for forked repositories

- _posts/docker/2015-05-25-services.md
To build minimal deployment containers you want to separate
building the artifact from building the deployment containers.
This gets documented here now.
> Docs for host volumes for deployment containers

- _posts/services/databases/2016-02-04-cassandra.md
**Note**, this PR requires an update to the build VMs, which is not live yet. As such the `sudo` command mentioned will not work on the current build VMs.
(Future) public URL https://codeship.com/documentation/databases/cassandra/
Do not merge yet, relies on codeship/checkbot#837 :)
> How to start the Cassandra service

- _posts/docker/languages/2015-08-28-java.md
To avoid logging messages when dependencies are being downloaded, the batch mode maven flag can be used. 
In the service definition file, the flag is already added, but in the steps file it was missing
> Add flag in docs to run the maven build in batch mode

- _posts/languages/2014-09-03-ruby.md
Explain how to install Nokogiri when using Ruby 2.3 using the system libraries and not the bundled versions.
> Use system libraries for Nokogiri on Ruby 2.3

- _posts/languages/2014-09-03-python.md
removing the old virtual environment caused the dependency cache to break beacuse of a missing folder.
> Rework how to cache Python 3 dependencies

- _posts/docker/languages/2015-08-27-ruby.md
The steps file mentioend a `specs` task, but the shell script defined the task as `spec`.
> Fix a typo in the Docker Ruby tutorial

- _posts/docker/tutorials/2015-09-07-caching.md
Fixes the issue with the codeblock in the info block on https://codeship.com/documentation/docker/caching/
> Fix the notice being displayed as a code block

- codeship-steps.yml
Don't run the deployment on branches starting with master
> Fix deployment regex

- _posts/docker/tutorials/2015-07-03-docker-push.md
- _posts/docker/tutorials/2015-08-12-docker-pull.md
- _posts/docker/tutorials/2015-09-04-docker-volumes.md
- _posts/docker/tutorials/2015-09-07-caching.md
- _posts/docker/tutorials/2015-09-14-ssh-key-authentication.md
- _posts/docker/tutorials/2015-09-15-encryption.md
- _posts/docker/tutorials/2015-12-17-dockercfg-services.md
Link to the `jet` CLI install document for each Docker tutorial referencing the CLI. Also added TOCs for those tutorials that didn't already have them enabled.
fixes #343
> Link to Jet Installation page from Docker Tutorials

- _posts/continuous-deployment/2014-09-03-deployment-with-ftp-sftp-scp.md
* Don't use the `$HOME` environment variable for (S)FTP based deployments and reference the home directory via `~/` instead.
* Use the same target directory for each of the examples (on the remote server).
> Don't use env variables in FTP/SFTP deploys

- .editorconfig
- _posts/docker/jet/2015-05-25-installation.md
- _sass/docs/_footnotes.scss
- _sass/rig/_variables.scss
- assets/css/docs.scss
Also added support for footnotes on articles, see the following two screenshots for how they look like.
**Link to a footnote in the text**
**Footnote including a link back**
> Jet Installation instructions for OS X via Homebrew Cask

- _config.yml
- _includes/comments.html
- _layouts/page.html
- _sass/docs/_page.scss
- feed.xml
This superseded #371 for adding comments to the documentation pages.
By default comments are enabled for all posts via the defaults in `_config.yaml`. If you want to disable comments for an individual post, add the following to the YAML front matter
```
comments: false
```
Threads will be created in the [Comments / Documentation](https://community.codeship.com/c/comments/documentation) subcategory.
```
https://codeship.com/documentation/feed.xml
```
> Add ability to embed Discourse comments on the Docs

- _config.yml
We use that URL in the feed we generate, which makes Discourse point to URLs including the www instead of the actual URL without it.
> Update site settings to remove the www from the URL

- _config.yml
- _plugins/sitemap.rb
* remove the subfolder from the URL (it's handled via the baseurl configuration entry)
* adapt the code for the sitemap to use the value from baseurl as well.
> Bugfix for RSS feeds used for Comments

- _layouts/category.html
- _layouts/tags.html
Use a single column on category and tag pages as was already configured for Docker related articles.
> Switch to single column overview pages

- _sass/rig/_global.scss
I have no idea why, but removing the `letter-spacing` brought back the third column. 
It would be great if @codebryo could take a look in a spare minute.
> Fix 3 column layout.

- _data/jet.yml
- _posts/docker/jet/2015-05-25-installation.md
- bin/build.sh
- bin/check_fork.sh
- bin/jet.sh
- bin/s3.sh
- bin/swiftype.sh
Link to the `sha256sums` file we generate when deploying a new version of `jet` and add a paragraph on how to verify the checksums (for Linux / Unix based OSes).
* Changed the `curl` commands to use the filenames from S3 so they match the filenames in the checksum file.
* Update the default `jet` version in the configuration files to `1.6.0`, this will be overwritten during deployment by the actual current version and is only used in local testing
* Update the `log` shell functions in a minor way.
See http://documentation.codeship.com/staging/jet-checksums/docker/installation/ for a staging deployment.
Requires codeship/jet#183
> Make checksum files for Jet available for download.

- _posts/languages/2014-09-03-nodejs.md
Add v6 to  the list of pre-installed NodeJS versions.
See https://github.com/nodejs/node/blob/master/CHANGELOG.md#2016-04-26-version-600-current-jasnell for the ChangeLog for the release.
Requires codeship/checkbot#872
> Update NodeJS, include v6

- codeship-steps.yml
`jekyll doctor` -- Search site and print specific deprecation warnings
> Run "jekyll doctor" during linting

- .gitignore
- Gemfile
- Gemfile.lock
- _config.yml
- _includes/head.html
See https://github.com/jekyll/jekyll-seo-tag for the plugin repository and more information about the plugin itself.
For standard articles the plugin will generate the following tags in the `<head>` of the page. (This is the data from [the Docker Welcome post](https://codeship.com/documentation/docker/introduction/).
```html
<title>Welcome to Codeship’s Docker Infrastructure</title>
<meta property="og:title" content="Welcome to Codeship’s Docker Infrastructure" />
<meta name="description" content="Welcome to Codeship’s Docker Infrastructure, the new way to run your tests on Codeship. Enjoy full customizability. Easily mirror your Development, Test and Production Environments with full parity. The underlying build infrastructure, based on Docker, allows for customized definition of the …
```
> Add the Jekyll SEO Plugin

- Dockerfile
this resulted in Jekyll exiting with the following error message: `Error:  getaddrinfo: Name or service not known`
> Fix a bug with parameters to CMD

- Gemfile
- Gemfile.lock
Upgrade to [Jekyll 3.1.6](https://github.com/jekyll/jekyll/releases), staging deploy available at http://documentation.codeship.com/staging/jekyll-3.1.6/
> Update Ruby based dependencies

- _lifecycle.json
- codeship-steps.yml
With the previous setup a deployment to e.g. `staging/feature-a` could deploy a new version of AWS lifecycle configuration and other similar metadata.
This change limits those steps to the `master` branch only.
Added some other (minor) changes
* Moved the `encrypted_dockercfg_path` directive to the group steps. That way we don't have to specify it on each step.
* Extended the AWS S3 lifecycle configuration with a new directive for deleting incomplete multipart uploads. We shouldn't need this, but AWS recommends it in their docs, and it doesn't hurt us.
* Fixed the indentation of child steps to match the other occurrences
> Deploy Metadata only for the master branch

- _includes/comments.html
google crawlers are picking up the following error from Discourse's embedded comment widget:
```
https://community.codeship.com/embed/comments?embed_url=https%3A%2F%2Fcodeship.com%2Fdocumentation%2Ftroubleshooting%2Fbuilds-are-not-triggered%2F Failed to load resource: the server responded with a status of 403 (Forbidden)
```
After browsing meta.discourse.org and the rest of the internet, the issue lies on the permission of the `embed` folder. Since we are using a hosted version of discourse, we are not able to fix it ourselves. 
As a work around so the google crawlers doesn't pick this up, I added some meta data to not index or follow the URL in this PR.
We may not be able to track traffic from `codeship.com/documentation` when someone clicks on the **Continue Discussion** button
Source …
> added meta data to stop comments from being indexed and followed

- _posts/troubleshooting/2014-09-10-builds-are-not-triggered.md
Removing the doc snippet with the workaround to merging branches. As of 7/1, all bitbucket projects will have the new API configured, so fast forwarding commits is no longer needed. 
This PR and the community announcement will be sent out tomorrow after the changes merge to production https://community.codeship.com/t/bitbucket-webhook-integration/1060.
> removing bitbucket issues

- _posts/docker/tutorials/2015-12-17-dockercfg-services.md
Some auth generator services require access to the local filesystem in order to write the generated auth file. If you attempt to run any of these services using a remote Docker host (AWS, Digital Ocean) it will fail because it doesn't have access to write to your local host.
> Generator tutorial -- warning about remote Docker hosts

- _posts/languages/2014-09-03-php.md
`--prefer-source` doesn't work well in combination with the dependency cache and forces a re-install of (most) dependencies.
> Don't pass --prefer-source for caching reasons

- _posts/docker/tutorials/2015-09-07-caching.md
> Fixing broken link in cache tutorial

- bin/build.sh
For the `master` branch, generate the site twice, once at the root of the destination
folder and once in the `/documentation` subfolder.
This is a preparatory step for moving the documentation from
http://codeship.com/documentation to http://documentation.codeship.com. In a further PR
we will need to update the `robots.txt` to allow robots access directly via the bucket and
the S3 website configuration to redirect switch redirects to the new location.
> Deploy the master branch to the bucket root too

- bin/build.sh
Building the version deployed to the root of the bucket caused an exception within Jekyll regarding stack level during the cleanup tasks.
We now build the root level version inside the `/site/root` folder and move it to the `/site` folder afterwards.
We also build the version after the version for the `/site/documentation` subfolder.
> Build the root level version in a subdir and move

- _posts/services/databases/2014-08-28-postgresql.md
- external/heroku.md
we export both versions `PG_USER`, `PGUSER` and `PG_PASSWORD`, `PGPASSWORD`.
this updates the docs to reference the official version going forward
https://www.postgresql.org/docs/8.4/static/libpq-envars.html
> update postgres env variables

- bin/s3.sh
- codeship-steps.yml
- robots.txt
* Allow robots to index the site
* Move the robots.txt to a standard file and remove the special configuration. Deploy it to each staging, private or master deployment.
**Merge after switching to the [http://documentation.codeship.com] subdomain**
> Deploy robots.txt via standard deploy

- _includes/head.html
- google1a85968316265362.html
Add the required HTML file to verify the https://documentation.codeship.com domain for Google Webmaster Tools
> Google Webmaster Tools verification

- _website.json
We missed a redirect from the old _Getting Started_ guide to the new one. Google still links to the old URL, so let's redirect it :)
After this is merged https://documentation.codeship.com/docker/getting-started/ should redirect to https://documentation.codeship.com/docker-guide/getting-started/
> Redirect "docker/getting-started" to "docker-guide/getting-started"

- _posts/integrations/2014-09-02-api.md
This removes the code block from the info section on http://documentation.codeship.com/integrations/api/
> Fix code block for the API info block

- _sass/docs/_page.scss
What is currently is
With my change
> Fixing inconsistent padding top and bottom on `tag` elements

- _config.yml
- _includes/header.html
* fix wording "Documentations" (is correct on main site)
* fix link to go to documentation homepage instead of baseurl
> Fix header link for docs

- _posts/faq/2014-09-12-codeship-badge.md
The documentation page at https://documentation.codeship.com/faq/codeship-badge/ shows a _Project Not Found_ error, because the UUID for the _Documentation_ project changed when switching to the Docker Infrastructure.
This PR updates the URL with the new UUID and makes the badge shiny and green again.
> Update badge URL for the Documentation project

- _posts/faq/2014-09-10-enabling-access-to-servers.md
We're moving in to a VPC in AWS.
This means that we our networking is going to change. Our instances will be situated in a new Security group within our VPC. 
I would hold off merging this, until we are ready to release the VPC changes :+1:
> Update FAQ to account for move to AWS VPC

- _website.json
With the redesign from #517 and reorganization of the articles some of the older redirects aren't required any more.
> Clean up redirect rules

- _sass/docs/_page.scss
Apparently, sometimes the browser calculates the browser width wrong when using `vw` units.
Switching to % fixes that.
> Fix vw caused rounding error

- _layouts/default.html
- _sass/docs/_page.scss
I fixed the behavior of the page sometimes to break.
The Main reason seems to be that there was a critical `.Sidebar` element wrapped in another `.Sidebar` element.
Fixed and verified.
> Fix sidebar behavior

- _includes/footer.html
* noticed that Codeship logo isn't in docs footer (taking care of that another time)
> Add Instagram Link in Footer

- _includes/meta.html
- _layouts/page.html
Tags are still included in meta tags and used by Swiftype, but don't show up for the user.
Reason being that Jekyll doesn't support tags for arbitrary collections and we can't generate tag overview pages at the moment.
> Hide tags on the documentation pages

- bin/s3.sh
- codeship-steps.yml
For each of the pages generated by the `jekyll-redirect-from` from gem, create a website redirect as documented on https://aws.amazon.com/blogs/aws/amazon-s3-support-for-website-redirects/
The script ins this PR looks through the generated site searching for the meta refresh tag, gets the target URL and then pushes the same file to AWS S3 with the added `--website-redirect-location` option set to the target URL.
That option will trigger a 301 permanent redirect on CloudFront.
Staging build available at https://app.codeship.com/projects/102044/builds/9dc53ef9-cb78-4707-aed3-84a9c014b811 and deployed to https://documentation.codeship.com/staging/s3-redirects-take1/.
See e.g. https://documentation.codeship.com/staging/s3-redirects-take1/databases/cassandra/  which redirects (via HTTP) to …
> S3 Redirects

- _website.json
The AWS CLI complains about an empty object, so we need to remove it completely.
> Completely remove the RoutingRules

- _docker/getting-started/services.md
Hey all,
We had some outdated information on our services docs page.
- caching info was incorrect
- The "new version" of Docker Compose syntax is V3; we should speak more generally about supporting version headers. We do support a majority of fields from V2 and V3 syntax, so stating that we don't support it is also a bit inaccurate.
> Update docker services 

- _docker/getting-started/build-arguments.md
- _docker/getting-started/encryption.md
- _docker/getting-started/services.md
These updates add documentation for the support of build arguments. The following keys are added to the services file:
`args:` (nested in build)
`encrypted_args` (nested in build)
`encrypted_args_file` (nested in build)
In addition, this PR includes updates to the `encryption` article to include instructions for encrypting a build args file, as well as a tutorial article for build arguments.
https://docs.docker.com/engine/reference/builder/#/arg
https://docs.docker.com/compose/compose-file/#/args
https://www.pivotaltracker.com/epic/show/3195541
> Add documentation for build args to services and encryption pages

- _website.json
The error caused only one redirect rule to be picked up.
I already created the second redirect via the AWS console, but this will make sure it is persisted.
> Fix a syntax error

- _pro/getting-started/services.md
Hey all,
We used to just have a subset of `unsupported` Docker Compose features. With the V2 updates, some customers are unclear about whether we now support just the syntax, or every single key that is available in V2. This should clear that up.
> Updating list of unsupported Docker compose features

- _pro/getting-started/services.md
The Docker `labels` feature applies to all Docker objects -- images, containers, networks, volumes, basically anything you can imagine. While we don't support `labels` for labelling running containers, images can be labeled using the `LABEL` instruction in the Dockerfile.
> additional clarity around image labels

- _pro/getting-started/installation.md
Tested this locally and it should do the trick to get that bit.ly link working again.
> Add redirect for bit.ly/codeship-jet-tool

- Dockerfile
- package.json
Installing Yarn via npm is being deprecated.  This will now install Yarn as recommended by the project.
https://yarnpkg.com/en/docs/install#linux-tab
> Update Yarn installation

- _includes/documentation_header.html
It is difficult to know which collection an article belongs to when you're browsing.  This is a subtle change that will highlight the active collection based on the article you are viewing.
> Highlight the active collection

- _pro/getting-started/cli.md
https://documentation.codeship.com/pro/cli/ is currently showing a 404 error :(
> Redirect /pro/cli/ to the CLI installation doc

- _pro/getting-started/build-arguments.md
- _pro/getting-started/encryption.md
This removes the 'private beta' message on build args doc articles. This should be merged along with the public release of build arguments. https://www.pivotaltracker.com/story/show/136353997
> Remove private beta note for build args docs

- Dockerfile
- _pro/getting-started/handling-secrets.md
Also, `MAINTAINER` is being deprecated, so I did some cleanup.
> Fixing table display and styling on Handling Secrets page

- _basic/languages-frameworks/php.md
Hey guys,
Your [PHP docs](https://documentation.codeship.com/basic/languages-frameworks/php/#phpunit) have a snippet explaining how to change the global composer version on the VM build. This PR addresses a couple things that are slightly out.
1. The `--update-with-dependencies` option for removing a Composer package has been deprecated since [1.0.0-beta2](https://github.com/composer/composer/blob/6c51006309c1692351f4e7f8395616a5946f5e42/CHANGELOG.md#100-beta2---2016-03-27) and results in a warning message. The old behaviour is now the default unless `--no-update-with-dependencies` is specified.
2. The syntax for requiring a package, although functional, does not match that of the Composer docs. Have updated to match.
Thanks!
> Remove deprecated option and fix require syntax in PHPUnit docs

- _general/account/guides/deployment-with-kubernetes.md
Was getting the following message when starting the docs site locally:
```
Liquid Warning: Liquid syntax error (line 85): [:dot, "."] is not a valid expression in "{{ .Timestamp }}" in /docs/_general/account/guides/deployment-with-kubernetes.md
```
The following change should allow `{{ .Timestamp }}` to just display rather than being treated as markup.
> Fix formatting

- _pro/continuous-deployment/azure.md
- _pro/getting-started/build-arguments.md
- _pro/getting-started/caching.md
- _pro/getting-started/custom-notifications.md
- _pro/getting-started/docker-push.md
- _pro/getting-started/dockercfg-services.md
- _pro/getting-started/getting-started-part-five.md
- _pro/getting-started/getting-started-part-four.md
- _pro/getting-started/getting-started-part-two.md
- _pro/getting-started/getting-started.md
- _pro/getting-started/image-push-fails.md
- _pro/getting-started/services-and-databases.md
- _pro/getting-started/services.md
- _pro/languages-frameworks/go.md
- _pro/languages-frameworks/java.md
- _pro/languages-frameworks/nodejs.md
- _pro/languages-frameworks/php.md
- _pro/languages-frameworks/python.md
- _pro/languages-frameworks/ruby.md
- codeship-services.yml
we say that use of `dockerfile_path` is deprecated, but almost all examples used it 😄 
this PR should correct the examples
> correcting use of dockerfile_path key

- _sass/docs/_page.scss
Only using !important short-term until paid account lets us term off branding.
> Force removing branding on ratings

- _basic/getting-started/parallelci.md
URLs should show as links now and changing the Node repo is based on customer feedback.
> Fix links and update Node repo

- README.md
Also, remove the badge for waffle.io (which we aren't using)
> Don't keep Docker containers around for one off commands

- _pro/continuous-deployment/ssh-deploy.md
- _pro/getting-started/cloning-repos.md
- Turning existing SSH article into multi-repo article
- Creating separate SSH deployment article
Added cards to Trello to circle back and improve code examples for both, but have short-term need for example to be up.
> Draft one articles for repo scenarios

- Gemfile
- Gemfile.lock
- Rakefile
- yarn.lock
And some groundwork to make this easier.
I added Rake tasks for common tasks we need to run
* `rake build` builds the Docker image
* `rake serve` serves the documentation via Docker on port `4000` of the Docker host
* `rake update` updates Ruby and NodeJS based dependencies
* `rake lint` runs the linters, all via Docker containers
I also ran `rake update` to get the latest versions of all dependencies and I removed the explicit dependency on Rouge, which is now handled by Jekyll itself. (Rouge wasn't always the default highlighter for Jekyll, but has been since a couple months.)
> Dependency Updates

- _plugins/ruby_versions_helper.rb
Post release, remember to:
```
aws s3 rm --recursive s3://codeship.io/checkbot/builds/ruby
```
> ruby files have moved due to changes made in the checkbot provisioning epic

- _general/account/permissions.md
* added new section for "Security" and moved other, permission related sections above that
* added section explaining difference between repository level permissions and access level
* added section with workaround for accounts without repo level permission of admin
* changed SCM sections to headers
> expanding on different types of permissions and what we need

- .gitignore
- Rakefile
- package.json
- yarn.lock
* Update all dependencies from `package.json` to their latest versions
* Add `tmp/*` to `.gitignore` (running `jet steps`, will generate the site in `tmp/site` and with the current setup we could end up with unwanted code in the repository)
* Added a Rake task to run `jet steps`
> Update Ruby and NodeJS based dependencies

- _basic/builds-and-configuration/parallelci.md
This previous PR (https://github.com/codeship/documentation/pull/698) seemed to get lost in the shuffle.  Adding it back in.
> Add link back from a previous PR

- Gemfile.lock
- package.json
- yarn.lock
Update `autoprefixer` and `gulp-postcss` to their latest available releases.
> Update Ruby and Node.js based dependencies

- _config.yml
- _includes/zendesk.html
- _layouts/default.html
Widget and enabled features are configurable via the _config.yml file.
At the moment the widget is enabled, but Zendesk Chat is not.
> Add the Zendesk widget to documentation pages

- _basic/continuous-deployment/deployment-to-google-app-engine.md
[Community discussion](https://community.codeship.com/t/how-to-deploy-node-js-with-appengine/4112/14) acknowledged our lack of support for node.js with google app engine.
Discussion as well on a [pivotal tracker ticket](https://www.pivotaltracker.com/story/show/146398621) regarding the need for an overhaul.
So at the very least, I've gone ahead with removing our stated support of node.js as well as edited a line for clarification.
> removed stated support for node, added emphasis to supported languages

- _general/integrations/codeclimate.md
Copy/pasting the `cc-test-reporter` after command into Test Steps resulted in the build failing as `$` returns an error where as `$?` returns the last pid exit code.
> Fix cc-test-reporter after command

- _pro/continuous-deployment/google-app-engine.md
- _pro/continuous-deployment/google-cloud.md
- _pro/continuous-deployment/google-container.md
Add basic instructions on how to deploy to Google App Engine from Codeship Pro.
> Google App Engine deployment instructions for Codeship Pro

- _general/integrations/codeclimate.md
The code snippet to report coverage after parallel runs to CodeClimate was missing it's second line (based on code we used to report coverage in Mothership and CodeClimate docs here: https://github.com/codeclimate/test-reporter#low-level-usage)
> Update parallel coverage reporting code

- _basic/continuous-integration/keep-build-artifacts.md
https://codeship.zendesk.com/agent/tickets/14426
User expected an `artifact.zip` file to be automatically generated in the build and cited our documentation as proof.
> changed line to imply artifact.zip is not auto generated

- _layouts/page.html
- _sass/docs/_page.scss
Adapt the design of the feedback block to look similar to warnings and info blocks and re-use most of the CSS.
Staging deployment available at https://documentation.codeship.com/staging/feedback-block/pro/continuous-deployment/google-cloud/ (this article shows all 3 currently used blocks, `info`, `warning` and the always shown `feedback` block)
Screenshot from the above article
> Bring the feedback block in line with info/warnings

- _general/integrations/assertible.md
Hey Codeship team! This PR adds a new docs page for integrating with [Assertible](https://assertible.com). I was talking about this w/ Mo, and wanted to get up an initial draft so y'all can take a look and I can fix any issues or make any necessary updates.
I used the Rollbar and GhostInspector pages as a 'template' for this one, so I think everything is structured correctly. But I'm more than happy to make any changes.
For both Codeship Pro and Basic, I've got these sections:
- Setting your API token
- Triggering tests during a build
- Running tests after a deployment
Thanks for reviewing! (cc @moritzplassnig)
> Check in integration documentation for Assertible

- CONTRIBUTING.md
GitHub's help link to the Pull Request page was outdated and I updated it with the latest link.
> Fixed PR link

- Gemfile
- Gemfile.lock
This PR upgrades to `shipyard 0.2.7` now that shipyard is up and running on mothership as well.
> Upgrade Shipyard 0.2.7

- _pro/continuous-deployment/ssh-deploy.md
Ran into issue recently where user was not able to effectively reformat their multi-line rsa secret key.
Marko was able to provide a one liner docker command. Adding to docs for all future one line formatting needs.
> docker command for formatting keys

- bin/packages.sh
* Disable the warning about a non-constant source
* Make use of the `CI_DEBUG_*` environment variables if they are set.
Those variables are not set by default, but there are ways to inject them into the debug VM during login. Get in touch if you want to know how to do this :)
(There was no new AMI, so no actual updates to the installed packages.)
> Minor updates to the packages.sh script

- _sass/rig/_global.scss
This fixes some inline code blocks (nested beneath anchor tags) still showing up in the old styles
> Quick (and dirty) fix for some inline code blocks

- _general/projects/builds-are-not-triggered.md
* Fix an issue with duplicated code below the GitHub section
* Move the status page paragraph to an info block and to the top of the page.
> Update builds not triggered article

- _basic/builds-and-configuration/set-environment-variables.md
It was in the docs, but it doesn't show up on the documentation page.
> Fix annotation about CI_PULL_REQUEST

- _includes/head.html
- index.html
The jekyll-seo-tag plugin adds a title tag to the page as well, and we don’t use categories any longer (which allows us to remove a lot of the custom logic)
I checked tag and collection index pages, and the titles are the same without that additional logic.
> Fix duplicate title tag

- _basic/continuous-deployment/deployment-to-aws-lambda.md
- _basic/continuous-deployment/deployment-to-digitalocean.md
- _basic/continuous-deployment/deployment-with-ftp-sftp-scp.md
- _basic/continuous-integration/browser-testing.md
- _basic/continuous-integration/run-a-command-in-the-background.md
- _basic/languages-frameworks/nodejs.md
- _pro/builds-and-configuration/build-arguments.md
- _pro/builds-and-configuration/cli.md
- _pro/builds-and-configuration/environment-variables.md
- _pro/builds-and-configuration/services.md
- _pro/builds-and-configuration/steps.md
- _pro/continuous-deployment/aws.md
- _pro/continuous-deployment/heroku.md
@mlocher The idea here would be to note when we ship this and then measure 30/60/90 days, in GA, organic search traffic to these pages to see if pages per session and bounce rate changes, as well as look as next page path to see if these links are being used.
This will help us figure out if this is an effective way to assist search traffic and therefore we should roll it out across all articles or if we should revisit how this is being done.
Edit: To clarify, these articles were picked because they're our most popular organic search articles and so make the best test.
> Search breadcrumbs

- _general/integrations/rollbar.md
The basic deployment interface doesn't allow for multi-line commands, and the original version fails in Codeship.
> Fix basic rollbar script

- _data/docker.yml
[DO NOT MERGE]
https://github.com/codeship/jet-base-ami/pull/105
I couldn't find any other references to the Docker version, so please let me know if I missed something.
> Update published Docker version to 17.10

- _data/menus.yml
v2 is getting ready to go out of Beta, so we shouldn't be pointing to v1 anymore
> updating API link to point to v2 instead of v1

- _general/integrations/api.md
Redirects should always end with a slash otherwise Jekyll will create e.g. an `api.html` which correctly redirects, but is never linked to.
> Fix redirects

- _pro/builds-and-configuration/cli.md
As of now we're going to move to use our own Homebrew Cask as it gives us more control over when we release jet (we don't have to wait for the homebrew-cask people to merge our PRs).
Im updating the docs to reflect this.
I'm going to work with the homebrew-cask team to deprecate or remove or existing cask there.
We are also changing the way our Changelog is managed. It will not be managed manually and stored as CHANGELOG.md in the releases directory on s3, so we should probably talk about how we keep the Release Notes page up to date with this in the future.
> Update Jet docs to point to our custom cask

- _pro/builds-and-configuration/cli.md
Fix to match the same heading size as the other commands
> Fix heading titles for `cleanup` and `validate`

- _general/account/whitelisting.md
removing the beta label from the whitelisting documentation article. 
shouldn't merge until actually released
> removing beta label from whitelisting documentation

- _basic/databases/postgresql.md
```
$ psql -p 5437
psql (10.3 (Ubuntu 10.3-1.pgdg14.04+1))
```
> PostgreSQL 10.2 moves to 10.3

- _basic/continuous-integration/browser-testing.md
Version 1.0.0 is out now, so installing with npm is the best option.
> Update SlimerJS steps

- _pro/quickstart/getting-started.md
Instruction for generating Gemfile.lock, corresponding ci-guide updated for [Ruby 2.5.0](https://github.com/codeship/ci-guide/pull/10) (issues with support for Redis on 2.2.1).
> generate Gemfile.lock with Docker command

- _basic/builds-and-configuration/access-to-other-repositories.md
- _basic/continuous-integration/git-submodules.md
Recent user attempted to implement Codeship Basic suggestions on Codeship Pro project. Resolution is to move to Basic doc space. Redirect added to continue supporting common error link raised on Codeship Basic builds.
> moving access to other repositories doc page to basic space

- _pro/continuous-deployment/heroku.md
without db migration exit code enabled, a failing migration may still result in a "successful" build
> add --exit-code flag to heroku deployment

- _data/docker.yml
- _pro/builds-and-configuration/services.md
Update docs to reflect that we are now using Docker v18.03 for Codeship Pro. 
Also update to _Note_ paragraphs to use the `csnote` helper instead.
> Docker 18.03

- _config.yml
- _layouts/categories-default.html
- _layouts/categories.html
- _layouts/default.html
This will likely need some refactoring, but the constraints are:
- The SEO plugin title metadata seems not to be used anywhere, as we have default titles overriding in all cases. So, it's useless and in the case of injecting the title into the header.html it created duplicate <title>s
- Jekly frontmatter is yaml and won't take variables, so the title can't be set on the actual category HTML layout page itself as far as I can figure, has to be one level above in a template
> Letting category pages have titles

- _pro/builds-and-configuration/steps.md
User recently pointed out that blocking of push steps via `jet steps` is not noted in our documentation.
> add warning that 'jet steps' will only run push steps with --push flag

- _includes/head.html
Favicon is not currently loading I think because the codeship.com favicon redirects to HubSpot. Grabbing it from the Codeship app works instead.
> Fix favicon

- _basic/databases/cassandra.md
- _basic/databases/rethinkdb.md
- _basic/languages-frameworks/dart.md
- _basic/languages-frameworks/go.md
- _basic/languages-frameworks/java-and-jvm-based-languages.md
- _basic/languages-frameworks/meteor.md
- _basic/languages-frameworks/php.md
- _basic/languages-frameworks/python.md
- _basic/languages-frameworks/ruby.md
- _basic/services/elasticsearch.md
- _general/integrations/custom-integration.md
realized we had multiple references to e.g. "sudo is not available" or "use this script to avoid sudo" etc.
> removing old references to sudo not being available

- Rakefile
Updates HTMLProofer to skip checking canonical links.
This is a [known issue](https://github.com/gjtorikian/html-proofer/issues/170) with the tool and this PR [implements the fix](https://github.com/gjtorikian/html-proofer/issues/170#issuecomment-384980061) using the `url_swap` option to make the canonical link relative instead of absolute.
Now HTMLProofer should pass when adding a new article or adding a new tag to an existing article.
> Skip checking canonical links with HTMLProofer

- _data/menus.yml
- _pro/common-issues/containers-slow-to-exit.md
The start of a 'Common Issues' section of the CodeShip Pro documentation
> command step hangs when dependent container setup with shell form CMD

- _general/projects/notifications.md
Clarified that 'restart build' will not trigger the recovered notification hook.
-general/projects/notifications.md
"Note: does not trigger when using 'Restart Build' from the console"
> Recovered notification clarification.

- yarn.lock
Credits to @joesiewert for connecting the dots on the recent [security issue with fstream-map](https://github.com/dominictarr/event-stream/issues/116).
Updated npm packages to no longer use compromised dependency.
> updated npm packages

- _pro/builds-and-configuration/environment-variables.md
`env_var` does nothing, I believe the correct directive is `env_file`
> Enviroment file directive error

- _basic/languages-frameworks/rust.md
- _pro/builds-and-configuration/steps.md
Feedback from a customer was that it wasn't clear that you didn't have to approve every paused build to get all the changes out.
This is more of a stop-gap as it's likely more of a UX issue than a documentation issue
> Manual approval updates

- _includes/footer.html
The Codeship account has been shut down and the link now gives a 404
> Remove Google+ link from footer

- _pro/builds-and-configuration/cloning-repos.md
I was stuck for quite a while today trying to figure out why my ssh key wasn't working. Turns out it was because I had `encrypted_args_file` under `app` instead of `build`.
Am I a moron? Probably. An example would have helped though, so I thought I'd add one in case someone else finds themselves in the same situation. :tada:
> Add an example and slightly change wording

- .spelling
- _basic/continuous-integration/browser-testing.md
- _general/about/getting_started_with_ci.md
The CasperJS site is down (maybe permanently?) and the GitHub repo indicates it is no longer maintained: https://github.com/casperjs/casperjs
> Remove CasperJS

- _general/integrations/codeclimate.md
- _general/integrations/rancher.md
- _general/projects/builds-are-not-triggered.md
- _pro/quickstart/docker-101.md
Hi,
While testing an [open-source tool](https://github.com/errata-ai/vale) I'm developing, I came across a few instances of repeated words in your documentation. I went ahead and fixed the obvious cases in the PR, but there are a few more:
```console
_general/integrations/percy.md
71:144   error  'integration' is repeated!  vale.Repetition 
79:104   error  'integration' is repeated!  vale.Repetition 
117:144  error  'integration' is repeated!  vale.Repetition 
127:94   error  'integration' is repeated!  vale.Repetition 
```
In the cases above, it appears that the issue may be an incorrect word (i.e., should it be "*integration instructions*"?):
> You can find specific integration integration for calling Percy from your test specs [at the Percy …
> Fix repeated word typos

- _includes/footer.html
The Codeship account has been shut down and the link now gives a 404
> Remove Instagram link from footer

- Gemfile.lock
Addresses [image build warning](https://app.codeship.com/projects/102044/builds/ee1a88e6-e478-48f2-bdee-6ee416fa52dd?line=61f3005d-dfb9-4fc9-82f1-ead6e9fc65bd&service=documentation) by ensuring Gemfile.lock is generated with version of Bundler present in image.
> set version of bundler to 1.17.2

- Rakefile
This link is frequently down so will have HTMLProofer ignore it
> Ignore checking nip.io link

- _includes/footer.html
The Codeship account has been shut down and the link now fails
> Remove Facebook link from footer

- gulpfile.js
- package.json
The [update](https://github.com/codeship/documentation/pull/1524) to [Autoprefixer 9.6.0](https://github.com/postcss/autoprefixer/releases/tag/9.6.0) introduced an upcoming deprecation on the `post-process` step of the build:
> Replace Autoprefixer browsers option to Browserslist config.
Use browserslist key in package.json or .browserslistrc file.
> Using browsers option cause some error. Browserslist config 
can be used for Babel, Autoprefixer, postcss-normalize and other tools.
> If you really need to use option, rename it to overrideBrowserslist.
> Learn more at:
https://github.com/browserslist/browserslist#readme
https://twitter.com/browserslist
This should resolve it by moving to the Browserslist configuration.
> Switch to Browserslist for Autoprefixer

- _basic/builds-and-configuration/parallel-tests.md
This page still said 20 parallel builds.
> Changed parallel branch number to 5 as shown on trial page.

- _layouts/page.html
This will fix all the pages that specific "This article is for CodeShip *product_name*"
> Last of the Codeship to CodeShip for product indicator

- yarn.lock
Got https://github.com/scalableminds/gulp-image-resize/pull/19 merged which should clear the GitHub security warnings for an outdated version of lodash.
> Bump gulp-image-resize

- Rakefile
These links frequently have issues so will have HTMLProofer ignore them
> Ignore checking lftp.yar.ru links

- Rakefile
- _general/integrations/rollbar.md
HTMLProofer has been failing recently. This fixes a Rollbar link and also ignores Twitter links. Twitter started returning 429 rate limit errors recently because this is likely trying to test too many Twitter links at once during the scan.
> Fix HTMLProofer scan

- _general/about/permissions.md
This section was only for the legacy OAuth app
> SHIP-1616 - Remove comments that refer to legacy OAuth app
